version: '3.8'

services:
  # Neon Local Proxy Service
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisition-neon-local
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    volumes:
      # Optional: Persist branches per Git branch
      - ./.neon_local/:/tmp/.neon_local
      - ./.git/HEAD:/tmp/.git/HEAD:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acquisition-app-dev
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    volumes:
      # Mount source code for development (hot reload)
      - ./src:/app/src
      - ./package.json:/app/package.json
    depends_on:
      neon-local:
        condition: service_healthy
    restart: unless-stopped
    command: ["node", "--watch", "src/index.js"]

networks:
  default:
    name: acquisition-dev-network